version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis:6379
    networks:
      - backend
    volumes:
      - file-data:/data
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - backend
    volumes:
      - redis-data:/data

networks:
  backend:
volumes:
  redis-data:
  file-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: d/shared
